'use client';

import { useEffect, useState } from 'react';
import Link from 'next/link';
import { useParams } from 'next/navigation';
import { createClient } from '@/lib/supabase/client';

export default function GroupPage(){const {id}=useParams<{id:string}>();const supabase=createClient();const [group,setGroup]=useState<any>(null);const [members,setMembers]=useState<any[]>([]);const [payouts,setPayouts]=useState<any[]>([]);const [error,setError]=useState('');
 useEffect(()=>{(async()=>{const {data:g,error:ge}=await supabase.from('chilimba_groups').select('*').eq('id',id).single();if(ge){setError(ge.message);return}setGroup(g);const {data:ms}=await supabase.from('group_members').select('id,user_id,role,status,payout_position,profiles(full_name,phone)').eq('group_id',id).order('payout_position');setMembers(ms||[]);const {data:ps}=await supabase.from('payouts').select('*').eq('group_id',id).order('payout_position');setPayouts(ps||[])})()},[id,supabase]);
 if(error)return <main className="shell"><p className="notice" role="alert">{error}</p><Link href="/groups">Back to groups</Link></main>;if(!group)return <main className="shell"><section className="card"><p>Loading chilimba…</p></section></main>;const pool=Number(group.contribution_amount)*members.length;
 return <main className="shell"><nav className="topbar"><Link href="/groups">← Groups</Link><nav><Link href={`/groups/${id}/contributions`}>Contributions</Link><Link href={`/groups/${id}/members`}>Members</Link><Link href={`/groups/${id}/admin`}>Admin</Link></nav></nav><section className="hero"><p className="eyebrow">ACTIVE CHILIMBA · ZMW</p><h1>{group.name}</h1><p>K{Number(group.contribution_amount).toLocaleString()} · {group.frequency} · {members.length} members · Transparent payout order.</p></section><section className="stats"><div className="stat"><span>Cycle payout</span><strong>K{pool.toLocaleString()}</strong><small>Current group pool</small></div><div className="stat"><span>Members</span><strong>{members.length}</strong><small>Active participants</small></div><div className="stat"><span>Frequency</span><strong>{group.frequency}</strong><small className="positive">● Active cycle</small></div></section><section className="dashboard-grid"><section className="card"><div className="section-head"><div><p className="eyebrow">PEOPLE</p><h2>Members & payout order</h2></div><Link className="pill" href={`/groups/${id}/members/invite`}>+ Invite</Link></div>{members.length===0?<p className="muted">No members yet.</p>:members.map((m,i)=><div className="member" key={m.id}><span className="avatar">{(m.profiles?.full_name||'?')[0]}</span><div><strong>{m.profiles?.full_name||m.profiles?.phone||'Member'}</strong><small>Position #{m.payout_position||i+1}</small></div><span className="pill">{m.role}</span></div>)}</section><section className="card"><p className="eyebrow">GROUP ACTIONS</p><h2>Manage this circle</h2><div className="quick-actions"><Link className="action" href={`/groups/${id}/contributions"><b>₭ Contributions</b><span>Track every payment</span></Link><Link className="action" href={`/groups/${id}/members`}><b>♧ Members</b><span>People and payout order</span></Link><Link className="action" href={`/groups/${id}/admin`}><b>◈ Admin</b><span>Financial controls</span></Link></div></section></section><section className="card" style={{marginTop:18}}><div className="section-head"><div><p className="eyebrow">PAYOUT SCHEDULE</p><h2>Who receives next?</h2></div></div>{payouts.length===0?<p className="muted">Payout schedule will appear after the group cycle is configured.</p>:payouts.map(p=><div className="payout" key={p.id}><span className="avatar">{p.payout_position}</span><div><strong>{p.scheduled_date}</strong><small>{p.status}</small></div><strong>K{Number(p.amount).toLocaleString()}</strong></div>)}</section><nav className="mobile-nav"><Link href="/dashboard">⌂<span>Home</span></Link><Link className="active" href="/groups">♧<span>Groups</span></Link><Link href="/member">₭<span>Pay</span></Link><Link href="/transactions">◷<span>History</span></Link><Link href="/profile">♙<span>Profile</span></Link></nav></main>}
