'use client';

import {useEffect,useMemo,useState} from 'react';import Link from 'next/link';import {createClient} from '@/lib/supabase/client';import LogoutButton from '@/components/logout-button';
export default function MemberHome(){const supabase=createClient();const[rows,setRows]=useState<any[]>([]);const[loading,setLoading]=useState(true);const[paying,setPaying]=useState<string|null>(null);const[message,setMessage]=useState('');const[payment,setPayment]=useState<any>(null);const[phone,setPhone]=useState('');
async function load(){const{data:{user}}=await supabase.auth.getUser();if(!user){window.location.href='/login';return}const{data}=await supabase.from('contributions').select('id,group_id,due_date,amount,status,paid_at,chilimba_groups(id,name,frequency),group_members!inner(user_id,payout_position)').eq('group_members.user_id',user.id).order('due_date');setRows(data||[]);setLoading(false)}useEffect(()=>{load()},[]);const pending=useMemo(()=>rows.filter(r=>r.status==='pending'),[rows]);const paid=useMemo(()=>rows.filter(r=>r.status==='paid'),[rows]);const totalDue=pending.reduce((s,r)=>s+Number(r.amount),0);const totalPaid=paid.reduce((s,r)=>s+Number(r.amount),0);
async function pay(row:any){setPaying(row.id);setMessage('');const r=await fetch('/api/payments/initiate',{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({contribution_id:row.id,phone,provider:'moneyunify'})});const d=await r.json();if(!r.ok){setMessage(d.error||'Unable to start payment.');setPaying(null);return}setPayment({row,transaction_id:d.transaction_id,status:d.status});setMessage(d.status==='pending'?'Payment request sent. Check your phone and approve it.':'Payment started.');setPaying(null);}
async function verify(){if(!payment)return;const r=await fetch('/api/payments/verify',{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({transaction_id:payment.transaction_id})});const d=await r.json();setPayment((p:any)=>({...p,status:d.status}));setMessage(d.status==='successful'?'Payment confirmed successfully.':d.status==='pending'?'Still waiting for approval…':`Payment ${d.status}.`);await load()}
useEffect(()=>{if(!payment||payment.status!=='pending')return;const timer=setInterval(verify,5000);return()=>clearInterval(timer)},[payment]);
if(loading)return <main className="shell"><section className="card"><p>Loading your savings…</p></section></main>;
return <main className="shell"><header className="topbar"><Link href="/dashboard">← Dashboard</Link><LogoutButton/></header><section><span className="eyebrow">MEMBER HOME</span><h1>Your savings</h1><p className="muted">Pay your Chilimba contribution securely through MoneyUnify.</p></section><section className="stats"><div className="card"><span>Due</span><strong>K{totalDue.toLocaleString()}</strong></div><div className="card"><span>Paid</span><strong>K{totalPaid.toLocaleString()}</strong></div><div className="card"><span>Records</span><strong>{rows.length}</strong></div></section>{message&&<section className="card"><p role="status">{message}</p></section>}<section className="card"><h2>Mobile number</h2><input type="tel" value={phone} onChange={e=>setPhone(e.target.value)} placeholder="097 123 4567"/><small>Use the number registered with MTN, Airtel or Zamtel.</small></section><section className="card"><h2>Next contributions</h2>{pending.length===0?<p className="muted">You're up to date. 🎉</p>:pending.slice(0,5).map(r=><div className="payout" key={r.id}><div><strong>{r.chilimba_groups?.name}</strong><small>Due {r.due_date} · {r.chilimba_groups?.frequency}</small></div><div><strong>K{Number(r.amount).toLocaleString()}</strong><button onClick={()=>pay(r)} disabled={paying===r.id||!!payment&&payment.status==='pending'}>{paying===r.id?'Starting…':'Pay with mobile money'}</button></div></div>)}</section>{payment&&<section className="card"><h2>Payment status</h2><p>{payment.status==='pending'?'📱 Check your phone and approve the MoneyUnify request. We are checking automatically.':payment.status==='successful'?'✅ Payment confirmed.':`Payment status: ${payment.status}`}</p>{payment.status==='pending'&&<button onClick={verify}>Check now</button>}</section>}<section className="card"><h2>Payment history</h2>{paid.slice(-5).reverse().map(r=><div className="payout" key={r.id}><div><strong>{r.chilimba_groups?.name}</strong><small>Paid {r.paid_at?new Date(r.paid_at).toLocaleDateString():'—'}</small></div><strong>K{Number(r.amount).toLocaleString()}</strong><span className="pill">Paid</span></div>)}{paid.length===0&&<p className="muted">Your completed payments will appear here.</p>}</section></main>}
