'use client';

import { useEffect, useMemo, useState } from 'react';
import Link from 'next/link';
import { createClient } from '@/lib/supabase/client';
import LogoutButton from '@/components/logout-button';

export default function MemberHome(){
 const supabase=createClient(); const [rows,setRows]=useState<any[]>([]); const [loading,setLoading]=useState(true); const [paying,setPaying]=useState<string|null>(null); const [message,setMessage]=useState('');
 useEffect(()=>{(async()=>{const {data:{user}}=await supabase.auth.getUser(); if(!user){window.location.href='/login';return;} const {data}=await supabase.from('contributions').select('id,group_id,due_date,amount,status,paid_at,chilimba_groups(id,name,frequency),group_members!inner(user_id,payout_position)').eq('group_members.user_id',user.id).order('due_date'); setRows(data||[]);setLoading(false)})()},[]);
 const pending=useMemo(()=>rows.filter(r=>r.status==='pending'),[rows]); const paid=useMemo(()=>rows.filter(r=>r.status==='paid'),[rows]); const totalDue=pending.reduce((s,r)=>s+Number(r.amount),0); const totalPaid=paid.reduce((s,r)=>s+Number(r.amount),0);
 async function pay(row:any){setPaying(row.id);setMessage('');const r=await fetch(`/api/groups/${row.group_id}/simulate-payment`,{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({contribution_id:row.id})});const d=await r.json();if(!r.ok)setMessage(d.error||'Payment failed');else setMessage('Payment recorded successfully.');const {data:{user}}=await supabase.auth.getUser();if(user){const {data}=await supabase.from('contributions').select('id,group_id,due_date,amount,status,paid_at,chilimba_groups(id,name,frequency),group_members!inner(user_id,payout_position)').eq('group_members.user_id',user.id).order('due_date');setRows(data||[])}setPaying(null)}
 if(loading)return <main className="shell"><section className="card"><p>Loading your savings…</p></section></main>;
 return <main className="shell"><header className="topbar"><Link href="/dashboard">← Dashboard</Link><LogoutButton/></header><section><span className="eyebrow">MEMBER HOME</span><h1>Your savings</h1><p className="muted">One clear view of what you owe, what you've paid and what's coming next.</p></section><section className="stats"><div className="card"><span>Due</span><strong>K{totalDue.toLocaleString()}</strong></div><div className="card"><span>Paid</span><strong>K{totalPaid.toLocaleString()}</strong></div><div className="card"><span>Records</span><strong>{rows.length}</strong></div></section>{message&&<section className="card"><p role="status">{message}</p></section>}<section className="card"><h2>Next contributions</h2>{pending.length===0?<p className="muted">You're up to date. 🎉</p>:pending.slice(0,5).map(r=><div className="payout" key={r.id}><div><strong>{r.chilimba_groups?.name}</strong><small>Due {r.due_date} · {r.chilimba_groups?.frequency}</small></div><div><strong>K{Number(r.amount).toLocaleString()}</strong><button onClick={()=>pay(r)} disabled={paying===r.id}>{paying===r.id?'…':'Pay'}</button></div></div>)}</section><section className="card"><h2>My groups</h2>{[...new Map(rows.map(r=>[r.group_id,r])).values()].map(r=><Link className="member" href={`/groups/${r.group_id}`} key={r.group_id}><span className="avatar">{r.chilimba_groups?.name?.[0]||'C'}</span><div><strong>{r.chilimba_groups?.name}</strong><small>Payout position #{r.group_members?.payout_position||'—'}</small></div><span>→</span></Link>)}{rows.length===0&&<p className="muted">No active chilimbas yet.</p>}</section><section className="card"><h2>Payment history</h2>{paid.slice(-5).reverse().map(r=><div className="payout" key={r.id}><div><strong>{r.chilimba_groups?.name}</strong><small>Paid {r.paid_at?new Date(r.paid_at).toLocaleDateString():'—'}</small></div><strong>K{Number(r.amount).toLocaleString()}</strong><span className="pill">Paid</span></div>)}{paid.length===0&&<p className="muted">Your completed payments will appear here.</p>}</section></main>
}
