'use client';

import { FormEvent, useState } from 'react';
import Link from 'next/link';
import { createClient } from '@/lib/supabase/client';
import { Brand } from '@/components/brand';

export default function LoginPage(){
 const supabase=createClient(); const [phone,setPhone]=useState(''); const [code,setCode]=useState(''); const [sent,setSent]=useState(false); const [busy,setBusy]=useState(false); const [message,setMessage]=useState(''); const [network,setNetwork]=useState('');
 const networks=[['mtn','MTN','MTN Mobile Money'],['airtel','Airtel','Airtel Money'],['zamtel','Zamtel','Zamtel Money']];
 async function send(e:FormEvent){e.preventDefault();setBusy(true);setMessage('');const normalized=phone.replace(/\s/g,'');if(!/^\+260\d{9}$/.test(normalized)){setMessage('Enter a valid Zambian number, e.g. +260 97 123 4567.');setBusy(false);return}const {error}=await supabase.auth.signInWithOtp({phone:normalized});if(error)setMessage(error.message);else{setSent(true);setMessage('OTP sent. Check your phone.')}setBusy(false)}
 async function verify(e:FormEvent){e.preventDefault();setBusy(true);setMessage('');const normalized=phone.replace(/\s/g,'');const {data,error}=await supabase.auth.verifyOtp({phone:normalized,token:code,type:'sms'});if(error)setMessage(error.message);else{if(data.user){await supabase.from('profiles').upsert({id:data.user.id,phone:normalized},{onConflict:'id'});}window.location.href='/dashboard';}setBusy(false)}
 return <main className="shell"><nav className="topbar"><Link href="/"><Brand compact/></Link><span>🇿🇲</span></nav><section className="hero"><p className="eyebrow">ZAMBIAN DIGITAL SAVINGS</p><h1>Save together.<br/>With confidence.</h1><p>Digital chilimbas built around trust, transparency and simple mobile money.</p></section><form className="card form-card" onSubmit={sent?verify:send}><div><p className="eyebrow">SECURE ACCESS</p><h2>{sent?'Verify your number':'Welcome back'}</h2></div>{!sent&&<><div><label>Zambian mobile number<input required type="tel" value={phone} onChange={e=>setPhone(e.target.value)} placeholder="+260 97 123 4567" /></label><small className="muted">We'll send a one-time verification code.</small></div><div><label>Mobile money network <span className="muted">(for payments)</span></label><div className="network-grid">{networks.map(([id,name,sub])=><button type="button" key={id} className={`network network-${id} ${network===id?'selected':''}`} onClick={()=>setNetwork(id)}><b>{name}</b><small>{sub}</small></button>)}</div></div></>}{sent&&<><label>Verification code<input required inputMode="numeric" autoComplete="one-time-code" value={code} onChange={e=>setCode(e.target.value)} placeholder="123456" /></label><button type="button" className="secondary full" onClick={()=>{setSent(false);setCode('');setMessage('')}}>Change number</button></>}{message&&<p role="status">{message}</p>}<button className="btn" disabled={busy}>{busy?'Please wait…':sent?'Verify & continue':'Send OTP'}</button></form><footer>🔒 Secure · 🇿🇲 Zambia · ZMW · Mobile money ready</footer></main>
}
