'use client';

import { FormEvent, useState } from 'react';
import { createClient } from '@/lib/supabase/client';

export default function LoginPage(){
 const supabase=createClient(); const [phone,setPhone]=useState(''); const [code,setCode]=useState(''); const [sent,setSent]=useState(false); const [busy,setBusy]=useState(false); const [message,setMessage]=useState('');
 async function send(e:FormEvent){e.preventDefault();setBusy(true);setMessage('');const normalized=phone.replace(/\s/g,'');const {error}=await supabase.auth.signInWithOtp({phone:normalized});if(error)setMessage(error.message);else{setSent(true);setMessage('OTP sent. Check your phone.')}setBusy(false)}
 async function verify(e:FormEvent){e.preventDefault();setBusy(true);setMessage('');const normalized=phone.replace(/\s/g,'');const {data,error}=await supabase.auth.verifyOtp({phone:normalized,token:code,type:'sms'});if(error)setMessage(error.message);else{if(data.user){await supabase.from('profiles').upsert({id:data.user.id,phone:normalized},{onConflict:'id'});}window.location.href='/dashboard';}setBusy(false)}
 return <main className="shell"><nav className="topbar"><strong>Chilimba Zambia</strong><span>🇿🇲</span></nav><section className="hero"><p className="eyebrow">ZAMBIAN DIGITAL SAVINGS</p><h1>Save together.<br/>With confidence.</h1><p>Digitize your chilimba with transparent contributions and payout schedules.</p></section><form className="card form-card" onSubmit={sent?verify:send}><h2>{sent?'Enter your OTP':'Sign in with your phone'}</h2>{!sent&&<label>Zambian phone number<input required type="tel" value={phone} onChange={e=>setPhone(e.target.value)} placeholder="+260 97 123 4567" /></label>}{sent&&<><label>Verification code<input required inputMode="numeric" autoComplete="one-time-code" value={code} onChange={e=>setCode(e.target.value)} placeholder="123456" /></label><button type="button" className="secondary full" onClick={()=>{setSent(false);setCode('');setMessage('')}}>Change number</button></>}{message&&<p role="status">{message}</p>}<button className="btn" disabled={busy}>{busy?'Please wait…':sent?'Verify & continue':'Send OTP'}</button></form><footer>Secure authentication · Zambia · ZMW</footer></main>
}
