'use client';

import { useEffect, useState } from 'react';
import Link from 'next/link';
import { useParams } from 'next/navigation';

export default function AdminPage(){const {id}=useParams<{id:string}>();const [data,setData]=useState<any>(null);const [error,setError]=useState('');
useEffect(()=>{fetch(`/api/groups/${id}/financials`).then(async r=>{const d=await r.json();if(!r.ok)throw new Error(d.error);setData(d)}).catch(e=>setError(e.message))},[id]);
if(error)return <main className="shell"><p role="alert">{error}</p><Link href={`/groups/${id}`}>Back to group</Link></main>;if(!data)return <main className="shell"><section className="card"><p>Loading financials…</p></section></main>;
const s=data.summary;return <main className="shell"><nav className="topbar"><Link href={`/groups/${id}`}>← Group</Link><strong>Admin</strong></nav><section><span className="eyebrow">FINANCIAL CONTROL</span><h1>{data.group.name}</h1><p className="muted">Transparent collection and payout readiness.</p></section><section className="stats"><div className="card"><span>Collected</span><strong>K{s.collected.toLocaleString()}</strong></div><div className="card"><span>Outstanding</span><strong>K{s.outstanding.toLocaleString()}</strong></div><div className="card"><span>Collection</span><strong>{s.collectionRate}%</strong></div></section><section className="card"><h2>Current payout</h2>{s.currentPayout?<><div className="payout"><div><strong>Position #{s.currentPayout.payout_position}</strong><small>Scheduled {s.currentPayout.scheduled_date}</small></div><strong>K{Number(s.currentPayout.amount).toLocaleString()}</strong></div><p>{s.currentCyclePaid} of {s.currentCycleTotal} contributions collected for this cycle.</p><span className="pill">{s.payoutReady?'READY FOR PAYOUT':'WAITING FOR CONTRIBUTIONS'}</span></>:<p className="muted">No scheduled payout yet. Generate the group schedule first.</p>}</section><section className="card"><h2>Member collection</h2>{data.members.map((m:any)=>{const mine=data.contributions.filter((c:any)=>c.member_id===m.id);const paid=mine.filter((c:any)=>c.status==='paid').reduce((a:any,c:any)=>a+Number(c.amount),0);const due=mine.reduce((a:any,c:any)=>a+Number(c.amount),0);return <div className="member" key={m.id}><span className="avatar">{(m.profiles?.full_name||'?')[0]}</span><div><strong>{m.profiles?.full_name||'Member'}</strong><small>Position #{m.payout_position} · K{paid.toLocaleString()} / K{due.toLocaleString()}</small></div><span>{due?Math.round(paid/due*100):0}%</span></div>})}</section></main>}
