'use client';

import { useEffect, useState } from 'react';
import { useParams } from 'next/navigation';
import Link from 'next/link';
import { createClient } from '@/lib/supabase/client';

export default function ContributionsPage(){const {id}=useParams<{id:string}>();const supabase=createClient();const [rows,setRows]=useState<any[]>([]);const [busy,setBusy]=useState<string|null>(null);const [error,setError]=useState('');
 async function load(){const {data}=await supabase.from('contributions').select('id,due_date,amount,status,paid_at,group_members!inner(user_id,profiles(full_name,phone))').eq('group_id',id).order('due_date').order('created_at');setRows(data||[])}
 useEffect(()=>{void load()},[id]);
 async function pay(row:any){setBusy(row.id);setError('');try{const r=await fetch(`/api/groups/${id}/simulate-payment`,{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({contribution_id:row.id})});const d=await r.json();if(!r.ok)setError(d.error||'Payment failed');await load()}catch{setError('Unable to update payment status.')}finally{setBusy(null)}}
 const paid=rows.filter(r=>r.status==='paid').reduce((s,r)=>s+Number(r.amount),0);const due=rows.filter(r=>r.status!=='paid').reduce((s,r)=>s+Number(r.amount),0);
 return <main className="shell"><nav className="topbar"><Link href={`/groups/${id}`}>← Group</Link><strong>Contributions</strong></nav><section className="hero"><p className="eyebrow">SAVINGS LEDGER</p><h1>Every kwacha<br/>accounted for.</h1><p>Transparent contribution records for every member and every cycle.</p></section><section className="stats"><div className="stat"><span>Collected</span><strong>K{paid.toLocaleString()}</strong><small className="positive">✓ Recorded</small></div><div className="stat"><span>Outstanding</span><strong>K{due.toLocaleString()}</strong><small>Pending contributions</small></div><div className="stat"><span>Members</span><strong>{new Set(rows.map(r=>r.group_members?.profiles?.phone)).size}</strong><small>Contribution records</small></div></section><section className="card">{error&&<p className="notice" role="alert">{error}</p>}{rows.length===0?<p className="muted">No contribution records yet. Generate the schedule first.</p>:rows.map(r=><div className="payout" key={r.id}><span className="avatar">{r.status==='paid'?'✓':'₭'}</span><div><strong>{r.group_members?.profiles?.full_name||'Member'}</strong><small>Due {r.due_date} · {r.status}</small></div><div><strong>K{Number(r.amount).toLocaleString()}</strong>{r.status==='pending'&&<button className="secondary" onClick={()=>void pay(r)} disabled={busy===r.id}>{busy===r.id?'Updating…':'Record payment'}</button>}</div></div>)}</section><nav className="mobile-nav"><Link href="/dashboard">⌂<span>Home</span></Link><Link className="active" href={`/groups/${id}`}>♧<span>Group</span></Link><Link href="/member">₭<span>Pay</span></Link><Link href="/transactions">◷<span>History</span></Link><Link href="/profile">♙<span>Profile</span></Link></nav></main>}
