import { NextRequest, NextResponse } from 'next/server';
import { createClient } from '@/lib/supabase/server';
import { getPaymentAdapter, normalizeZambianPhone, type PaymentProvider } from '@/lib/payments';

export async function POST(request:NextRequest,{params}:{params:Promise<{id:string}>}){const {id}=await params;const supabase=await createClient();const {data:{user}}=await supabase.auth.getUser();if(!user)return NextResponse.json({error:'Unauthorized'},{status:401});const {data:admin}=await supabase.from('group_members').select('role').eq('group_id',id).eq('user_id',user.id).eq('status','active').single();if(admin?.role!=='admin')return NextResponse.json({error:'Admin access required'},{status:403});
 const {payout_id}=await request.json();const {data:payout}=await supabase.from('payouts').select('id,group_id,recipient_member_id,amount,status,scheduled_date').eq('id',payout_id).eq('group_id',id).single();if(!payout)return NextResponse.json({error:'Payout not found'},{status:404});if(payout.status!=='scheduled')return NextResponse.json({error:`Payout is already ${payout.status}.`},{status:409});
 const {data:cycle}=await supabase.from('contributions').select('status').eq('group_id',id).eq('due_date',payout.scheduled_date);if(!cycle?.length||cycle.some(x=>x.status!=='paid'))return NextResponse.json({error:'Payout is not fully funded.'},{status:409});
 const {data:member}=await supabase.from('group_members').select('user_id,profiles(full_name,phone)').eq('id',payout.recipient_member_id).eq('group_id',id).single();if(!member)return NextResponse.json({error:'Payout recipient not found.'},{status:404});const profile:any=member.profiles;const parts=String(profile?.full_name||'Chilimba Member').trim().split(/\s+/);const firstName=parts.shift()||'Chilimba';const lastName=parts.join(' ')||'Member';const phone=normalizeZambianPhone(String(profile?.phone||''));const email=`${phone.replace('+','')}@chilimba.local`;
 const provider=(process.env.PAYMENT_PROVIDER||'sandbox') as PaymentProvider;const adapter=getPaymentAdapter(provider);if(!adapter.disburse)return NextResponse.json({error:'Selected payment provider does not support payouts.'},{status:400});const result=await adapter.disburse({payoutId:payout.id,groupId:id,userId:user.id,amount:Number(payout.amount),phone,firstName,lastName,email});
 const {data:tx,error:txError}=await supabase.from('payment_transactions').insert({user_id:user.id,group_id:id,direction:'outbound',status:result.status,provider,provider_transaction_id:result.reference,idempotency_key:`payout-${payout.id}`,amount:payout.amount,currency:'ZMW',metadata:{payout_id:payout.id,recipient_member_id:payout.recipient_member_id}}).select('id').single();if(txError)return NextResponse.json({error:txError.message},{status:400});
 const payoutStatus=result.status==='successful'?'paid':result.status==='failed'?'failed':'processing';const update:any={status:payoutStatus,payment_transaction_id:tx.id,approved_at:new Date().toISOString(),approved_by:user.id};if(result.status==='successful')update.paid_at=new Date().toISOString();const {error}=await supabase.from('payouts').update(update).eq('id',payout.id).eq('status','scheduled');if(error)return NextResponse.json({error:error.message},{status:400});return NextResponse.json({ok:true,payout_id:payout.id,transaction_id:tx.id,reference:result.reference,status:payoutStatus,provider});}
